[files]
extend-exclude = [
    # Search for Lorem ipsum: git -P grep -E '\b(Lorem|Nam|Morbi|Etiam|Nulla|Pellentesque|varius)\b'
    ".git/",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "\\bBig Sur\\b",
    "[0-9A-Za-z/+]{64}",
    #"\\\\p\\{Nd\\}",
]

[default.extend-words]
# Typos
"contiguities" = "continuities"
"intension" = "intention"
"intensional" = "intentional"
"intensionally" = "intentionally"
"intensionaly" = "intentionally"
"pervious" = "previous"
"perviously" = "previously"
"covert" = "convert"
"metho" = "method"
"coulnd" = "couldn"
"woulnd" = "wouldn"
"shoulnd" = "shouldn"
#"encrypter" = "encrypter"
#"invokable" = "invokable"
#"responsable" = "responsable"
"weather" = "whether"
"singed" = "signed"
"singing" = "signing"
"sqllite" = "sqlite"

[default.extend-identifiers]
ANDed = "ANDed"

#"get_post_stati" = "get_post_stati"
"Automattic" = "Automattic"
"HashiCorp" = "HashiCorp"
# Typos
"Github" = "GitHub"
"Wordpress" = "WordPress"
"Woocommerce" = "WooCommerce"
