[package]
name = "pod2"
version = "0.1.0"
edition = "2021"

[lib]
name = "pod2"
path = "src/lib.rs"

[dependencies]
hex = "0.4.3"
itertools = "0.14.0"
strum = "0.26"
strum_macros = "0.26"
anyhow = "1.0.56"
dyn-clone = "1.0.18"
# enabled by features:
plonky2 = { git = "https://github.com/0xPolygonZero/plonky2", optional = true }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
base64 = "0.22.1"
schemars = "1.0.0-alpha.17"
axum = "0.7.4"
axum-server = "0.6.0"
tokio = { version = "1.36.0", features = ["full"] }
tower-http = { version = "0.5.1", features = ["cors"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
ascent = "0.8.0"

[dev-dependencies]
hyper = { version = "1.1.0", features = ["full"] }
tower = { version = "0.4.13", features = ["util"] }
>>>>>>> 5eb347d (WIP web-based UI)

[features]
default = ["backend_plonky2"]
backend_plonky2 = ["plonky2"]
