[workspace]
resolver = "2"
members = ["pod2"]

[workspace.dependencies]
pod2 = { path = "pod2" }

hex = "0.4.3"
itertools = "0.14.0"
strum = "0.26"
strum_macros = "0.26"
anyhow = "1.0.56"
dyn-clone = "1.0.18"
