name: Rust Build with features

on:
  pull_request:
    branches: [ main ]
    types: [ready_for_review, opened, synchronize, reopened]
  push:
    branches: [ main ]

jobs:
  test:
    if: github.event.pull_request.draft == false
    name: Rust tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Build default
      run: cargo build
    - name: Build non-zk # check without the zk feature enabled
      run: cargo build --no-default-features --features backend_plonky2,mem_cache
    - name: Build metrics
      run: cargo build --features metrics
    - name: Build time
      run: cargo build --features time
    - name: Build disk_cache
      run: cargo build --no-default-features --features backend_plonky2,zk,disk_cache

