[default.extend-words]
groth = "groth" # to avoid it dectecting it as 'growth'
BA = "BA"
Ded = "Ded" # "ANDed", it thought "Ded" should be "Dead"
OT = "OT"
aks = "aks" # anchored keys
nin = "nin" # not in
kow = "kow" # key or wildcard
KOW = "KOW" # Key Or Wildcard
datas = "datas" # plural (for 'verifier_datas', a vector of 'verifier_data')
